[g1_robots]
g1_robot_030 ansible_host=192.168.90.30 robot_id=30 end_effector=dex1
g1_robot_060 ansible_host=192.168.90.60 robot_id=60 end_effector=dex1
g1_robot_062 ansible_host=192.168.90.62 robot_id=62 end_effector=dex1
g1_robot_063 ansible_host=192.168.90.63 robot_id=63 end_effector=dex1
g1_robot_065 ansible_host=192.168.90.65 robot_id=65 end_effector=dex1
g1_robot_068 ansible_host=192.168.90.68 robot_id=68 end_effector=brainco
g1_robot_069 ansible_host=192.168.90.69 robot_id=69 end_effector=brainco
g1_robot_070 ansible_host=192.168.90.70 robot_id=70 end_effector=brainco

[g1_robots:vars]
ansible_user=unitree
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o PreferredAuthentications=password -o PubkeyAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
