cameras:
   - device_name: ""
     topic_name: "cam_head"
     camera_type: "REALSENSE"
     image_width: 640
     image_height: 480
     frame_rate: 30
     compress_type: "MJPEG_COMPRESS"
     flip: false
     enable_socket_publish: true
     socket_publish_port: 5555
   - device_name: "/dev/cam_wrist_left"
     topic_name: "cam_wrist_left"
     camera_type: "V4L2"
     image_width: 640
     image_height: 480
     frame_rate: 30
     compress_type: "MJPEG_COMPRESS"
     flip: false
     enable_socket_publish: false
     socket_publish_port: 5555
   - device_name: "/dev/cam_wrist_right"
     topic_name: "cam_wrist_right"
     camera_type: "V4L2"
     image_width: 640
     image_height: 480
     frame_rate: 30
     compress_type: "MJPEG_COMPRESS"
     flip: false
     enable_socket_publish: false
     socket_publish_port: 5555

device_type: "G1_29_DOF"

pico:
  receiver:
    pose_82d_hz: 50
  teleop:
    enable: true
    publish_packet_json: true
    packet_topic: "/pico/teleop_packet"
    teleop_cmd_topic: "/fsm/teleop/cmd"
    sport_request_topic: "/api/sport/request"
    teleop_fsm_id: 505
    locomotion_fsm_id: 801

joints:
  hand_type: "dex1"  # none, inspire, dex1, brainco
  inspire:
    left_cmd_topic: "/inspire_hand/ctrl/l"
    right_cmd_topic: "/inspire_hand/ctrl/r"
    right_ip: "192.168.123.211"
    left_ip: "192.168.123.210"
    port: 6000
    device_id: 1
    angle_start_address: 1546
    angle_count: 6
  dex1:
    left_cmd_topic: "/dex1/left/cmd"
    right_cmd_topic: "/dex1/right/cmd"
    left_state_topic: "/dex1/left/state"
    right_state_topic: "/dex1/right/state"
  brainco:
    left_cmd_topic: "/brainco/left/cmd"
    right_cmd_topic: "/brainco/right/cmd"
    left_state_topic: "/brainco/left/state"
    right_state_topic: "/brainco/right/state"
