[g1_robots]
#g1_robot_017 ansible_host=192.168.90.17 robot_id=17 end_effector=none
#g1_robot_013 ansible_host=192.168.90.13 robot_id=13 end_effector=brainco
#g1_robot_020 ansible_host=192.168.90.20 robot_id=20 end_effector=dex1
g1_robot_068 ansible_host=192.168.90.68 robot_id=68 end_effector=brainco
#g1_robot_030 ansible_host=192.168.90.30 robot_id=30 end_effector=dex1
g1_robot_060 ansible_host=192.168.90.83 robot_id=60 end_effector=dex1

[g1_robots:vars]
ansible_user=unitree
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o PreferredAuthentications=password -o PubkeyAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
